var dir_4f208546d38190e788493c6962a4c7c8 =
[
    [ "backend", "dir_66a5469399c67a7bcd179366b8f79af4.html", "dir_66a5469399c67a7bcd179366b8f79af4" ],
    [ "external", "dir_ae15ba5bc50045fe20c951bbcb871b5f.html", "dir_ae15ba5bc50045fe20c951bbcb871b5f" ],
    [ "spmat", "dir_e645e514d13493cd87cf59c939956a2c.html", "dir_e645e514d13493cd87cf59c939956a2c" ],
    [ "backend.hpp", "backend_8hpp.html", null ],
    [ "cast.hpp", "cast_8hpp.html", "cast_8hpp" ],
    [ "constants.hpp", "constants_8hpp.html", "constants_8hpp" ],
    [ "devlist.hpp", "devlist_8hpp.html", "devlist_8hpp" ],
    [ "element_index.hpp", "element__index_8hpp.html", "element__index_8hpp" ],
    [ "fft.hpp", "fft_8hpp.html", null ],
    [ "gather.hpp", "gather_8hpp.html", null ],
    [ "generator.hpp", "generator_8hpp.html", "generator_8hpp" ],
    [ "mba.hpp", "mba_8hpp.html", [
      [ "mba", "classvex_1_1mba.html", "classvex_1_1mba" ]
    ] ],
    [ "multi_array.hpp", "multi__array_8hpp.html", "multi__array_8hpp" ],
    [ "multivector.hpp", "multivector_8hpp.html", "multivector_8hpp" ],
    [ "operations.hpp", "operations_8hpp.html", "operations_8hpp" ],
    [ "profiler.hpp", "profiler_8hpp.html", "profiler_8hpp" ],
    [ "random.hpp", "random_8hpp.html", null ],
    [ "reduce_by_key.hpp", "reduce__by__key_8hpp.html", "reduce__by__key_8hpp" ],
    [ "reductor.hpp", "reductor_8hpp.html", "reductor_8hpp" ],
    [ "sort.hpp", "sort_8hpp.html", "sort_8hpp" ],
    [ "spmat.hpp", "spmat_8hpp.html", "spmat_8hpp" ],
    [ "stencil.hpp", "stencil_8hpp.html", "stencil_8hpp" ],
    [ "tagged_terminal.hpp", "tagged__terminal_8hpp.html", "tagged__terminal_8hpp" ],
    [ "temporary.hpp", "temporary_8hpp.html", "temporary_8hpp" ],
    [ "types.hpp", "types_8hpp.html", null ],
    [ "util.hpp", "util_8hpp.html", "util_8hpp" ],
    [ "vector.hpp", "vector_8hpp.html", "vector_8hpp" ],
    [ "vector_pointer.hpp", "vector__pointer_8hpp.html", "vector__pointer_8hpp" ],
    [ "vector_view.hpp", "vector__view_8hpp.html", "vector__view_8hpp" ],
    [ "vexcl.hpp", "vexcl_8hpp.html", null ]
];