var hierarchy =
[
    [ "vex::Filter::CC", "structvex_1_1Filter_1_1CC.html", null ],
    [ "vex::backend::cuda::command_queue", "classvex_1_1backend_1_1cuda_1_1command__queue.html", null ],
    [ "vex::multivector< T, N >::const_element", "classvex_1_1multivector_1_1const__element.html", null ],
    [ "vex::backend::cuda::context", "classvex_1_1backend_1_1cuda_1_1context.html", null ],
    [ "vex::Context", "classvex_1_1Context.html", null ],
    [ "vex::Filter::Count", "structvex_1_1Filter_1_1Count.html", null ],
    [ "vex::backend::cuda::device", "classvex_1_1backend_1_1cuda_1_1device.html", null ],
    [ "vex::backend::cuda::device_vector< T >", "classvex_1_1backend_1_1cuda_1_1device__vector.html", null ],
    [ "vex::backend::cuda::device_vector< col_t >", "classvex_1_1backend_1_1cuda_1_1device__vector.html", null ],
    [ "vex::backend::cuda::device_vector< idx_t >", "classvex_1_1backend_1_1cuda_1_1device__vector.html", null ],
    [ "vex::backend::cuda::device_vector< int >", "classvex_1_1backend_1_1cuda_1_1device__vector.html", null ],
    [ "vex::backend::cuda::device_vector< real >", "classvex_1_1backend_1_1cuda_1_1device__vector.html", null ],
    [ "vex::backend::cuda::device_vector< size_t >", "classvex_1_1backend_1_1cuda_1_1device__vector.html", null ],
    [ "vex::backend::cuda::device_vector< val_t >", "classvex_1_1backend_1_1cuda_1_1device__vector.html", null ],
    [ "vex::multivector< T, N >::element", "classvex_1_1multivector_1_1element.html", null ],
    [ "vex::vector< T >::element", "classvex_1_1vector_1_1element.html", null ],
    [ "std::exception", null, [
      [ "std::runtime_error", null, [
        [ "vex::backend::cuda::error", "classvex_1_1backend_1_1cuda_1_1error.html", null ]
      ] ]
    ] ],
    [ "vex::Filter::Extension", "structvex_1_1Filter_1_1Extension.html", null ],
    [ "vex::FFT< Tin, Tout, Planner >", "structvex_1_1FFT.html", null ],
    [ "vex::generator::Function", "classvex_1_1generator_1_1Function.html", null ],
    [ "vex::generator::FunctorAdapter< Signature, Functor >", "structvex_1_1generator_1_1FunctorAdapter.html", null ],
    [ "vex::Filter::General", "structvex_1_1Filter_1_1General.html", null ],
    [ "vex::greater< T >", "structvex_1_1greater.html", null ],
    [ "vex::greater_equal< T >", "structvex_1_1greater__equal.html", null ],
    [ "vex::gslice< NDIM >", "structvex_1_1gslice.html", null ],
    [ "vex::gslice< NR >", "structvex_1_1gslice.html", null ],
    [ "vex::is_multivector_expression< T >", "structvex_1_1is__multivector__expression.html", null ],
    [ "vex::is_vector_expression< T >", "structvex_1_1is__vector__expression.html", null ],
    [ "vex::vector< T >::iterator_type< vector_type, element_type >", "classvex_1_1vector_1_1iterator__type.html", null ],
    [ "vex::generator::Kernel< NP >", "classvex_1_1generator_1_1Kernel.html", null ],
    [ "vex::less< T >", "structvex_1_1less.html", null ],
    [ "vex::less_equal< T >", "structvex_1_1less__equal.html", null ],
    [ "vex::MAX", "structvex_1_1MAX.html", null ],
    [ "vex::mba< NDIM, real >", "classvex_1_1mba.html", null ],
    [ "vex::MIN", "structvex_1_1MIN.html", null ],
    [ "vex::multivector< T, N >", "classvex_1_1multivector.html", null ],
    [ "vex::Filter::Name", "structvex_1_1Filter_1_1Name.html", null ],
    [ "vex::random::philox", "structvex_1_1random_1_1philox.html", null ],
    [ "vex::Filter::Platform", "structvex_1_1Filter_1_1Platform.html", null ],
    [ "vex::plus< T >", "structvex_1_1plus.html", null ],
    [ "vex::Filter::Position", "structvex_1_1Filter_1_1Position.html", null ],
    [ "vex::profiler< Clock >", "classvex_1_1profiler.html", null ],
    [ "vex::Random< T, Generator >", "structvex_1_1Random.html", null ],
    [ "vex::RandomNormal< T, Generator >", "structvex_1_1RandomNormal.html", null ],
    [ "vex::range", "structvex_1_1range.html", null ],
    [ "vex::Reductor< real, RDC >", "classvex_1_1Reductor.html", null ],
    [ "vex::slicer< NR >", "structvex_1_1slicer.html", null ],
    [ "vex::SpMat< val_t, col_t, idx_t >", "classvex_1_1SpMat.html", null ],
    [ "vex::SpMatCCSR< val_t, col_t, idx_t >", "structvex_1_1SpMatCCSR.html", null ],
    [ "vex::stencil< T >", "classvex_1_1stencil.html", null ],
    [ "vex::StencilOperator< T, width, center, Impl >", "classvex_1_1StencilOperator.html", null ],
    [ "vex::stopwatch< Clock >", "classvex_1_1stopwatch.html", null ],
    [ "vex::SUM", "structvex_1_1SUM.html", null ],
    [ "vex::random::threefry", "structvex_1_1random_1_1threefry.html", null ],
    [ "vex::Filter::Type", "structvex_1_1Filter_1_1Type.html", null ],
    [ "vex::vector< T >", "classvex_1_1vector.html", null ],
    [ "vex::Filter::Vendor", "structvex_1_1Filter_1_1Vendor.html", null ]
];