var namespacevex =
[
    [ "backend", "namespacevex_1_1backend.html", "namespacevex_1_1backend" ],
    [ "constants", "namespacevex_1_1constants.html", null ],
    [ "fft", "namespacevex_1_1fft.html", null ],
    [ "Filter", "namespacevex_1_1Filter.html", "namespacevex_1_1Filter" ],
    [ "generator", "namespacevex_1_1generator.html", "namespacevex_1_1generator" ],
    [ "random", "namespacevex_1_1random.html", "namespacevex_1_1random" ],
    [ "Random", "structvex_1_1Random.html", "structvex_1_1Random" ],
    [ "RandomNormal", "structvex_1_1RandomNormal.html", "structvex_1_1RandomNormal" ],
    [ "FFT", "structvex_1_1FFT.html", "structvex_1_1FFT" ],
    [ "Context", "classvex_1_1Context.html", "classvex_1_1Context" ],
    [ "mba", "classvex_1_1mba.html", "classvex_1_1mba" ],
    [ "multivector", "classvex_1_1multivector.html", "classvex_1_1multivector" ],
    [ "is_vector_expression", "structvex_1_1is__vector__expression.html", null ],
    [ "is_multivector_expression", "structvex_1_1is__multivector__expression.html", null ],
    [ "stopwatch", "classvex_1_1stopwatch.html", "classvex_1_1stopwatch" ],
    [ "profiler", "classvex_1_1profiler.html", "classvex_1_1profiler" ],
    [ "SUM", "structvex_1_1SUM.html", null ],
    [ "MAX", "structvex_1_1MAX.html", null ],
    [ "MIN", "structvex_1_1MIN.html", null ],
    [ "Reductor", "classvex_1_1Reductor.html", "classvex_1_1Reductor" ],
    [ "plus", "structvex_1_1plus.html", "structvex_1_1plus" ],
    [ "less", "structvex_1_1less.html", "structvex_1_1less" ],
    [ "less_equal", "structvex_1_1less__equal.html", "structvex_1_1less__equal" ],
    [ "greater", "structvex_1_1greater.html", "structvex_1_1greater" ],
    [ "greater_equal", "structvex_1_1greater__equal.html", "structvex_1_1greater__equal" ],
    [ "SpMatCCSR", "structvex_1_1SpMatCCSR.html", "structvex_1_1SpMatCCSR" ],
    [ "SpMat", "classvex_1_1SpMat.html", "classvex_1_1SpMat" ],
    [ "stencil", "classvex_1_1stencil.html", "classvex_1_1stencil" ],
    [ "StencilOperator", "classvex_1_1StencilOperator.html", "classvex_1_1StencilOperator" ],
    [ "vector", "classvex_1_1vector.html", "classvex_1_1vector" ],
    [ "gslice", "structvex_1_1gslice.html", "structvex_1_1gslice" ],
    [ "range", "structvex_1_1range.html", "structvex_1_1range" ],
    [ "slicer", "structvex_1_1slicer.html", "structvex_1_1slicer" ]
];