VexCL: vex Namespace Reference
vex Namespace Reference
Vector expression template library for OpenCL.
Namespaces
backend
Backend-specific functionality.
constants
Mathematical constants.
fft
Fast Fourier Transform.
Filter
Device filters.
generator
Kernel generation interface.
random
Random generators.
Classes
struct Random
A random generator.
struct RandomNormal
Returns normal distributed random numbers.
struct FFT
Fast Fourier Transform.
class Context
VexCL context holder.
class mba
Scattered data interpolation with multilevel B-Splines.
class multivector
Container for several vex::vectors.
struct is_vector_expression
Meta-filter for VexCL vector expressions.
struct is_multivector_expression
Meta-filter for VexCL multivector expressions.
class stopwatch
A stopwatch that computes the median and mean of individual timings.
class profiler
Class for gathering and printing OpenCL and Host profiling info.
struct SUM
Summation. Should be used as a template parameter for Reductor class.
struct MAX
Maximum element. Should be used as a template parameter for Reductor class.
struct MIN
Minimum element. Should be used as a template parameter for Reductor class.
class Reductor
Parallel reduction of arbitrary expression.
struct plus
Binary function object class whose call returns the result of adding its two arguments.
struct less
Function object class for less-than inequality comparison.
struct less_equal
Function object class for less-than-or-equal inequality comparison.
struct greater
Function object class for greater-than inequality comparison.
struct greater_equal
Function object class for greater-than-or-equal inequality comparison.
struct SpMatCCSR
Sparse matrix in CCSR format.
class SpMat
Sparse matrix in hybrid ELL-CSR format.
class stencil
Stencil.
class StencilOperator
User-defined stencil operator.
class vector
Device vector.
struct gslice
Generalized slice selector.
struct range
An index range for use with slicer class.
struct slicer
Slicing operator.
Functions
void push_compile_options (const backend::command_queue &q, const std::string &str)
Set global compute kernel compilation options for a given device.
void pop_compile_options (const backend::command_queue &q)
Rolls back changes to compile options.
void push_program_header (const backend::command_queue &q, const std::string &str)
Set global compute kernel header for a given device.
void pop_program_header (const backend::command_queue &q)
Rolls back changes to compile options.
void push_compile_options (const std::vector< backend::command_queue > &queue, const std::string &str)
Set global compute kernel compilation options for each device in queue list.
void pop_compile_options (const std::vector< backend::command_queue > &queue)
Rolls back changes to compile options for each device in queue list.
void push_program_header (const std::vector< backend::command_queue > &queue, const std::string &str)
Set global OpenCL program header for each device in queue list.
void pop_program_header (const std::vector< backend::command_queue > &queue)
Rolls back changes to compile options for each device in queue list.
const std::string & path_delim ()
Path delimiter symbol.
const std::string & appdata_path ()
Path to appdata folder.
std::string program_binaries_path (const std::string &hash, bool create=false)
Path to cached binaries.
std::string sha1 (const std::string &src)
Returns SHA1 hash of the string parameter.
template<typename T , class Expr >
casted_expession< T, Expr >::type cast (const Expr &expr)
Cast an expression to a given type.
template<typename Arg >
casted_expession< cl_float,
typename
boost::proto::result_of::make_expr
< boost::proto::tag::function,
convert_float_func, const Arg & >
::type > const convert_float (const Arg &arg)
template<typename Arg >
casted_expession< cl_float,
typename
boost::proto::result_of::make_expr
< boost::proto::tag::function,
as_float_func, const Arg & >
::type > const as_float (const Arg &arg)
template<typename Arg >
casted_expession< cl_float2,
typename
boost::proto::result_of::make_expr
< boost::proto::tag::function,
convert_float2_func, const Arg & >
::type > const convert_float2 (const Arg &arg)
template<typename Arg >
casted_expession< cl_float2,
typename
boost::proto::result_of::make_expr
< boost::proto::tag::function,
as_float2_func, const Arg & >
::type > const as_float2 (const Arg &arg)
template<typename Arg >
casted_expession< cl_float4,
typename
boost::proto::result_of::make_expr
< boost::proto::tag::function,
convert_float4_func, const Arg & >
::type > const convert_float4 (const Arg &arg)
template<typename Arg >
casted_expession< cl_float4,
typename
boost::proto::result_of::make_expr
< boost::proto::tag::function,
as_float4_func, const Arg & >
::type > const as_float4 (const Arg &arg)
template<typename Arg >
casted_expession< cl_float8,
typename
boost::proto::result_of::make_expr
< boost::proto::tag::function,
convert_float8_func, const Arg & >
::type > const convert_float8 (const Arg &arg)
template<typename Arg >
casted_expession< cl_float8,
typename
boost::proto::result_of::make_expr
< boost::proto::tag::function,
as_float8_func, const Arg & >
::type > const as_float8 (const Arg &arg)
template<typename Arg >
casted_expession< cl_float16,
typename
boost::proto::result_of::make_expr
< boost::proto::tag::function,
convert_float16_func, const
Arg & >::type > const convert_float16 (const Arg &arg)
template<typename Arg >
casted_expession< cl_float16,
typename
boost::proto::result_of::make_expr
< boost::proto::tag::function,
as_float16_func, const Arg & >
::type > const as_float16 (const Arg &arg)
template<typename Arg >
casted_expession< cl_double,
typename
boost::proto::result_of::make_expr
< boost::proto::tag::function,
convert_double_func, const Arg & >
::type > const convert_double (const Arg &arg)
template<typename Arg >
casted_expession< cl_double,
typename
boost::proto::result_of::make_expr
< boost::proto::tag::function,
as_double_func, const Arg & >
::type > const as_double (const Arg &arg)
template<typename Arg >
casted_expession< cl_double2,
typename
boost::proto::result_of::make_expr
< boost::proto::tag::function,
convert_double2_func, const
Arg & >::type > const convert_double2 (const Arg &arg)
template<typename Arg >
casted_expession< cl_double2,
typename
boost::proto::result_of::make_expr
< boost::proto::tag::function,
as_double2_func, const Arg & >
::type > const as_double2 (const Arg &arg)
template<typename Arg >
casted_expession< cl_double4,
typename
boost::proto::result_of::make_expr
< boost::proto::tag::function,
convert_double4_func, const
Arg & >::type > const convert_double4 (const Arg &arg)
template<typename Arg >
casted_expession< cl_double4,
typename
boost::proto::result_of::make_expr
< boost::proto::tag::function,
as_double4_func, const Arg & >
::type > const as_double4 (const Arg &arg)
template<typename Arg >
casted_expession< cl_double8,
typename
boost::proto::result_of::make_expr
< boost::proto::tag::function,
convert_double8_func, const
Arg & >::type > const convert_double8 (const Arg &arg)
template<typename Arg >
casted_expession< cl_double8,
typename
boost::proto::result_of::make_expr
< boost::proto::tag::function,
as_double8_func, const Arg & >
::type > const as_double8 (const Arg &arg)
template<typename Arg >
casted_expession< cl_double16,
typename
boost::proto::result_of::make_expr
< boost::proto::tag::function,
convert_double16_func, const
Arg & >::type > const convert_double16 (const Arg &arg)
template<typename Arg >
casted_expession< cl_double16,
typename
boost::proto::result_of::make_expr
< boost::proto::tag::function,
as_double16_func, const Arg & >
::type > const as_double16 (const Arg &arg)
template<typename Arg >
casted_expession< cl_char,
typename
boost::proto::result_of::make_expr
< boost::proto::tag::function,
convert_char_func, const Arg & >
::type > const convert_char (const Arg &arg)
template<typename Arg >
casted_expession< cl_char,
typename
boost::proto::result_of::make_expr
< boost::proto::tag::function,
as_char_func, const Arg & >
::type > const as_char (const Arg &arg)
template<typename Arg >
casted_expession< cl_char2,
typename
boost::proto::result_of::make_expr
< boost::proto::tag::function,
convert_char2_func, const Arg & >
::type > const convert_char2 (const Arg &arg)
template<typename Arg >
casted_expession< cl_char2,
typename
boost::proto::result_of::make_expr
< boost::proto::tag::function,
as_char2_func, const Arg & >
::type > const as_char2 (const Arg &arg)
template<typename Arg >
casted_expession< cl_char4,
typename
boost::proto::result_of::make_expr
< boost::proto::tag::function,
convert_char4_func, const Arg & >
::type > const convert_char4 (const Arg &arg)
template<typename Arg >
casted_expession< cl_char4,
typename
boost::proto::result_of::make_expr
< boost::proto::tag::function,
as_char4_func, const Arg & >
::type > const as_char4 (const Arg &arg)
template<typename Arg >
casted_expession< cl_char8,
typename
boost::proto::result_of::make_expr
< boost::proto::tag::function,
convert_char8_func, const Arg & >
::type > const convert_char8 (const Arg &arg)
template<typename Arg >
casted_expession< cl_char8,
typename
boost::proto::result_of::make_expr
< boost::proto::tag::function,
as_char8_func, const Arg & >
::type > const as_char8 (const Arg &arg)
template<typename Arg >
casted_expession< cl_char16,
typename
boost::proto::result_of::make_expr
< boost::proto::tag::function,
convert_char16_func, const Arg & >
::type > const convert_char16 (const Arg &arg)
template<typename Arg >
casted_expession< cl_char16,
typename
boost::proto::result_of::make_expr
< boost::proto::tag::function,
as_char16_func, const Arg & >
::type > const as_char16 (const Arg &arg)
template<typename Arg >
casted_expession< cl_uchar,
typename
boost::proto::result_of::make_expr
< boost::proto::tag::function,
convert_uchar_func, const Arg & >
::type > const convert_uchar (const Arg &arg)
template<typename Arg >
casted_expession< cl_uchar,
typename
boost::proto::result_of::make_expr
< boost::proto::tag::function,
as_uchar_func, const Arg & >
::type > const as_uchar (const Arg &arg)
template<typename Arg >
casted_expession< cl_uchar2,
typename
boost::proto::result_of::make_expr
< boost::proto::tag::function,
convert_uchar2_func, const Arg & >
::type > const convert_uchar2 (const Arg &arg)
template<typename Arg >
casted_expession< cl_uchar2,
typename
boost::proto::result_of::make_expr
< boost::proto::tag::function,
as_uchar2_func, const Arg & >
::type > const as_uchar2 (const Arg &arg)
template<typename Arg >
casted_expession< cl_uchar4,
typename
boost::proto::result_of::make_expr
< boost::proto::tag::function,
convert_uchar4_func, const Arg & >
::type > const convert_uchar4 (const Arg &arg)
template<typename Arg >
casted_expession< cl_uchar4,
typename
boost::proto::result_of::make_expr
< boost::proto::tag::function,
as_uchar4_func, const Arg & >
::type > const as_uchar4 (const Arg &arg)
template<typename Arg >
casted_expession< cl_uchar8,
typename
boost::proto::result_of::make_expr
< boost::proto::tag::function,
convert_uchar8_func, const Arg & >
::type > const convert_uchar8 (const Arg &arg)
template<typename Arg >
casted_expession< cl_uchar8,
typename
boost::proto::result_of::make_expr
< boost::proto::tag::function,
as_uchar8_func, const Arg & >
::type > const as_uchar8 (const Arg &arg)
template<typename Arg >
casted_expession< cl_uchar16,
typename
boost::proto::result_of::make_expr
< boost::proto::tag::function,
convert_uchar16_func, const
Arg & >::type > const convert_uchar16 (const Arg &arg)
template<typename Arg >
casted_expession< cl_uchar16,
typename
boost::proto::result_of::make_expr
< boost::proto::tag::function,
as_uchar16_func, const Arg & >
::type > const as_uchar16 (const Arg &arg)
template<typename Arg >
casted_expession< cl_short,
typename
boost::proto::result_of::make_expr
< boost::proto::tag::function,
convert_short_func, const Arg & >
::type > const convert_short (const Arg &arg)
template<typename Arg >
casted_expession< cl_short,
typename
boost::proto::result_of::make_expr
< boost::proto::tag::function,
as_short_func, const Arg & >
::type > const as_short (const Arg &arg)
template<typename Arg >
casted_expession< cl_short2,
typename
boost::proto::result_of::make_expr
< boost::proto::tag::function,
convert_short2_func, const Arg & >
::type > const convert_short2 (const Arg &arg)
template<typename Arg >
casted_expession< cl_short2,
typename
boost::proto::result_of::make_expr
< boost::proto::tag::function,
as_short2_func, const Arg & >
::type > const as_short2 (const Arg &arg)
template<typename Arg >
casted_expession< cl_short4,
typename
boost::proto::result_of::make_expr
< boost::proto::tag::function,
convert_short4_func, const Arg & >
::type > const convert_short4 (const Arg &arg)
template<typename Arg >
casted_expession< cl_short4,
typename
boost::proto::result_of::make_expr
< boost::proto::tag::function,
as_short4_func, const Arg & >
::type > const as_short4 (const Arg &arg)
template<typename Arg >
casted_expession< cl_short8,
typename
boost::proto::result_of::make_expr
< boost::proto::tag::function,
convert_short8_func, const Arg & >
::type > const convert_short8 (const Arg &arg)
template<typename Arg >
casted_expession< cl_short8,
typename
boost::proto::result_of::make_expr
< boost::proto::tag::function,
as_short8_func, const Arg & >
::type > const as_short8 (const Arg &arg)
template<typename Arg >
casted_expession< cl_short16,
typename
boost::proto::result_of::make_expr
< boost::proto::tag::function,
convert_short16_func, const
Arg & >::type > const convert_short16 (const Arg &arg)
template<typename Arg >
casted_expession< cl_short16,
typename
boost::proto::result_of::make_expr
< boost::proto::tag::function,
as_short16_func, const Arg & >
::type > const as_short16 (const Arg &arg)
template<typename Arg >
casted_expession< cl_ushort,
typename
boost::proto::result_of::make_expr
< boost::proto::tag::function,
convert_ushort_func, const Arg & >
::type > const convert_ushort (const Arg &arg)
template<typename Arg >
casted_expession< cl_ushort,
typename
boost::proto::result_of::make_expr
< boost::proto::tag::function,
as_ushort_func, const Arg & >
::type > const as_ushort (const Arg &arg)
template<typename Arg >
casted_expession< cl_ushort2,
typename
boost::proto::result_of::make_expr
< boost::proto::tag::function,
convert_ushort2_func, const
Arg & >::type > const convert_ushort2 (const Arg &arg)
template<typename Arg >
casted_expession< cl_ushort2,
typename
boost::proto::result_of::make_expr
< boost::proto::tag::function,
as_ushort2_func, const Arg & >
::type > const as_ushort2 (const Arg &arg)
template<typename Arg >
casted_expession< cl_ushort4,
typename
boost::proto::result_of::make_expr
< boost::proto::tag::function,
convert_ushort4_func, const
Arg & >::type > const convert_ushort4 (const Arg &arg)
template<typename Arg >
casted_expession< cl_ushort4,
typename
boost::proto::result_of::make_expr
< boost::proto::tag::function,
as_ushort4_func, const Arg & >
::type > const as_ushort4 (const Arg &arg)
template<typename Arg >
casted_expession< cl_ushort8,
typename
boost::proto::result_of::make_expr
< boost::proto::tag::function,
convert_ushort8_func, const
Arg & >::type > const convert_ushort8 (const Arg &arg)
template<typename Arg >
casted_expession< cl_ushort8,
typename
boost::proto::result_of::make_expr
< boost::proto::tag::function,
as_ushort8_func, const Arg & >
::type > const as_ushort8 (const Arg &arg)
template<typename Arg >
casted_expession< cl_ushort16,
typename
boost::proto::result_of::make_expr
< boost::proto::tag::function,
convert_ushort16_func, const
Arg & >::type > const convert_ushort16 (const Arg &arg)
template<typename Arg >
casted_expession< cl_ushort16,
typename
boost::proto::result_of::make_expr
< boost::proto::tag::function,
as_ushort16_func, const Arg & >
::type > const as_ushort16 (const Arg &arg)
template<typename Arg >
casted_expession< cl_int,
typename
boost::proto::result_of::make_expr
< boost::proto::tag::function,
convert_int_func, const Arg & >
::type > const convert_int (const Arg &arg)
template<typename Arg >
casted_expession< cl_int,
typename
boost::proto::result_of::make_expr
< boost::proto::tag::function,
as_int_func, const Arg & >
::type > const as_int (const Arg &arg)
template<typename Arg >
casted_expession< cl_int2,
typename
boost::proto::result_of::make_expr
< boost::proto::tag::function,
convert_int2_func, const Arg & >
::type > const convert_int2 (const Arg &arg)
template<typename Arg >
casted_expession< cl_int2,
typename
boost::proto::result_of::make_expr
< boost::proto::tag::function,
as_int2_func, const Arg & >
::type > const as_int2 (const Arg &arg)
template<typename Arg >
casted_expession< cl_int4,
typename
boost::proto::result_of::make_expr
< boost::proto::tag::function,
convert_int4_func, const Arg & >
::type > const convert_int4 (const Arg &arg)
template<typename Arg >
casted_expession< cl_int4,
typename
boost::proto::result_of::make_expr
< boost::proto::tag::function,
as_int4_func, const Arg & >
::type > const as_int4 (const Arg &arg)
template<typename Arg >
casted_expession< cl_int8,
typename
boost::proto::result_of::make_expr
< boost::proto::tag::function,
convert_int8_func, const Arg & >
::type > const convert_int8 (const Arg &arg)
template<typename Arg >
casted_expession< cl_int8,
typename
boost::proto::result_of::make_expr
< boost::proto::tag::function,
as_int8_func, const Arg & >
::type > const as_int8 (const Arg &arg)
template<typename Arg >
casted_expession< cl_int16,
typename
boost::proto::result_of::make_expr
< boost::proto::tag::function,
convert_int16_func, const Arg & >
::type > const convert_int16 (const Arg &arg)
template<typename Arg >
casted_expession< cl_int16,
typename
boost::proto::result_of::make_expr
< boost::proto::tag::function,
as_int16_func, const Arg & >
::type > const as_int16 (const Arg &arg)
template<typename Arg >
casted_expession< cl_uint,
typename
boost::proto::result_of::make_expr
< boost::proto::tag::function,
convert_uint_func, const Arg & >
::type > const convert_uint (const Arg &arg)
template<typename Arg >
casted_expession< cl_uint,
typename
boost::proto::result_of::make_expr
< boost::proto::tag::function,
as_uint_func, const Arg & >
::type > const as_uint (const Arg &arg)
template<typename Arg >
casted_expession< cl_uint2,
typename
boost::proto::result_of::make_expr
< boost::proto::tag::function,
convert_uint2_func, const Arg & >
::type > const convert_uint2 (const Arg &arg)
template<typename Arg >
casted_expession< cl_uint2,
typename
boost::proto::result_of::make_expr
< boost::proto::tag::function,
as_uint2_func, const Arg & >
::type > const as_uint2 (const Arg &arg)
template<typename Arg >
casted_expession< cl_uint4,
typename
boost::proto::result_of::make_expr
< boost::proto::tag::function,
convert_uint4_func, const Arg & >
::type > const convert_uint4 (const Arg &arg)
template<typename Arg >
casted_expession< cl_uint4,
typename
boost::proto::result_of::make_expr
< boost::proto::tag::function,
as_uint4_func, const Arg & >
::type > const as_uint4 (const Arg &arg)
template<typename Arg >
casted_expession< cl_uint8,
typename
boost::proto::result_of::make_expr
< boost::proto::tag::function,
convert_uint8_func, const Arg & >
::type > const convert_uint8 (const Arg &arg)
template<typename Arg >
casted_expession< cl_uint8,
typename
boost::proto::result_of::make_expr
< boost::proto::tag::function,
as_uint8_func, const Arg & >
::type > const as_uint8 (const Arg &arg)
template<typename Arg >
casted_expession< cl_uint16,
typename
boost::proto::result_of::make_expr
< boost::proto::tag::function,
convert_uint16_func, const Arg & >
::type > const convert_uint16 (const Arg &arg)
template<typename Arg >
casted_expession< cl_uint16,
typename
boost::proto::result_of::make_expr
< boost::proto::tag::function,
as_uint16_func, const Arg & >
::type > const as_uint16 (const Arg &arg)
template<typename Arg >
casted_expession< cl_long,
typename
boost::proto::result_of::make_expr
< boost::proto::tag::function,
convert_long_func, const Arg & >
::type > const convert_long (const Arg &arg)
template<typename Arg >
casted_expession< cl_long,
typename
boost::proto::result_of::make_expr
< boost::proto::tag::function,
as_long_func, const Arg & >
::type > const as_long (const Arg &arg)
template<typename Arg >
casted_expession< cl_long2,
typename
boost::proto::result_of::make_expr
< boost::proto::tag::function,
convert_long2_func, const Arg & >
::type > const convert_long2 (const Arg &arg)
template<typename Arg >
casted_expession< cl_long2,
typename
boost::proto::result_of::make_expr
< boost::proto::tag::function,
as_long2_func, const Arg & >
::type > const as_long2 (const Arg &arg)
template<typename Arg >
casted_expession< cl_long4,
typename
boost::proto::result_of::make_expr
< boost::proto::tag::function,
convert_long4_func, const Arg & >
::type > const convert_long4 (const Arg &arg)
template<typename Arg >
casted_expession< cl_long4,
typename
boost::proto::result_of::make_expr
< boost::proto::tag::function,
as_long4_func, const Arg & >
::type > const as_long4 (const Arg &arg)
template<typename Arg >
casted_expession< cl_long8,
typename
boost::proto::result_of::make_expr
< boost::proto::tag::function,
convert_long8_func, const Arg & >
::type > const convert_long8 (const Arg &arg)
template<typename Arg >
casted_expession< cl_long8,
typename
boost::proto::result_of::make_expr
< boost::proto::tag::function,
as_long8_func, const Arg & >
::type > const as_long8 (const Arg &arg)
template<typename Arg >
casted_expession< cl_long16,
typename
boost::proto::result_of::make_expr
< boost::proto::tag::function,
convert_long16_func, const Arg & >
::type > const convert_long16 (const Arg &arg)
template<typename Arg >
casted_expession< cl_long16,
typename
boost::proto::result_of::make_expr
< boost::proto::tag::function,
as_long16_func, const Arg & >
::type > const as_long16 (const Arg &arg)
template<typename Arg >
casted_expession< cl_ulong,
typename
boost::proto::result_of::make_expr
< boost::proto::tag::function,
convert_ulong_func, const Arg & >
::type > const convert_ulong (const Arg &arg)
template<typename Arg >
casted_expession< cl_ulong,
typename
boost::proto::result_of::make_expr
< boost::proto::tag::function,
as_ulong_func, const Arg & >
::type > const as_ulong (const Arg &arg)
template<typename Arg >
casted_expession< cl_ulong2,
typename
boost::proto::result_of::make_expr
< boost::proto::tag::function,
convert_ulong2_func, const Arg & >
::type > const convert_ulong2 (const Arg &arg)
template<typename Arg >
casted_expession< cl_ulong2,
typename
boost::proto::result_of::make_expr
< boost::proto::tag::function,
as_ulong2_func, const Arg & >
::type > const as_ulong2 (const Arg &arg)
template<typename Arg >
casted_expession< cl_ulong4,
typename
boost::proto::result_of::make_expr
< boost::proto::tag::function,
convert_ulong4_func, const Arg & >
::type > const convert_ulong4 (const Arg &arg)
template<typename Arg >
casted_expession< cl_ulong4,
typename
boost::proto::result_of::make_expr
< boost::proto::tag::function,
as_ulong4_func, const Arg & >
::type > const as_ulong4 (const Arg &arg)
template<typename Arg >
casted_expession< cl_ulong8,
typename
boost::proto::result_of::make_expr
< boost::proto::tag::function,
convert_ulong8_func, const Arg & >
::type > const convert_ulong8 (const Arg &arg)
template<typename Arg >
casted_expession< cl_ulong8,
typename
boost::proto::result_of::make_expr
< boost::proto::tag::function,
as_ulong8_func, const Arg & >
::type > const as_ulong8 (const Arg &arg)
template<typename Arg >
casted_expession< cl_ulong16,
typename
boost::proto::result_of::make_expr
< boost::proto::tag::function,
convert_ulong16_func, const
Arg & >::type > const convert_ulong16 (const Arg &arg)
template<typename Arg >
casted_expession< cl_ulong16,
typename
boost::proto::result_of::make_expr
< boost::proto::tag::function,
as_ulong16_func, const Arg & >
::type > const as_ulong16 (const Arg &arg)
const Context & current_context ()
Returns reference to the latest instance of vex::Context.
elem_index element_index (size_t offset=0, size_t length=0)
When used in vector expression, returns current element index plus offset.
template<typename T >
void inclusive_scan (const vex::vector< T > &src, vex::vector< T > &dst)
Inclusive scan.
template<typename T >
void sort (vex::vector< T > &x)
Sort.
template<typename T >
std::ostream & operator<< (std::ostream &os, const symbolic< T > &sym)
Sends name of the symbolic variable to output stream.
template<class RDC , typename T , size_t NDIM, size_t NR>
reduced_vector_view< vector< T >
, NDIM, NR, RDC > reduce (const multi_array< T, NDIM > &m, const std::array< size_t, NR > &reduce_dims)
Reduce vex::multi_array along the specified dimensions.
template<class RDC , typename T , size_t NDIM>
reduced_vector_view< vector< T >
, NDIM, 1, RDC > reduce (const multi_array< T, NDIM > &m, size_t reduce_dim)
Reduce vex::multi_array along the specified dimension.
template<class T , size_t N>
void copy (const multivector< T, N > &mv, std::vector< T > &hv)
Copy multivector to host vector.
template<class T , size_t N>
void copy (const std::vector< T > &hv, multivector< T, N > &mv)
Copy host vector to multivector.
template<class T , size_t N>
std::ostream & operator<< (std::ostream &o, const vex::multivector< T, N > &t)
Download and print the vector elements.
template<class... Expr>
expression_tuple< std::tuple
< const Expr &...> > tie (const Expr &...expr)
Ties several vector expressions into writeable tuple.
void purge_kernel_caches ()
Clears cached OpenCL kernels, allowing to release OpenCL contexts.
void purge_kernel_caches (backend::kernel_cache_key key)
Clears cached OpenCL kernels, allowing to release OpenCL contexts.
void purge_kernel_caches (const std::vector< backend::command_queue > &queue)
Clears cached OpenCL kernels, allowing to release OpenCL contexts.
template<typename IKeys , typename OKeys , typename V , class Comp , class Oper >
int reduce_by_key (IKeys &&ikeys, vector< V > const &ivals, OKeys &&okeys, vector< V > &ovals, Comp comp, Oper oper)
Reduce by key algorithm.
template<typename K , typename V >
int reduce_by_key (vector< K > const &ikeys, vector< V > const &ivals, vector< K > &okeys, vector< V > &ovals)
Reduce by key algorithm.
template<typename T , class R >
const vex::Reductor< T, R > & get_reductor (const std::vector< backend::command_queue > &queue)
Returns a reference to a static instance of vex::Reductor<T,R>
template<typename T , class Oper >
void inclusive_scan (vector< T > const &input, vector< T > &output, T init, Oper oper)
Inclusive scan.
template<typename T >
void inclusive_scan (vector< T > const &input, vector< T > &output, T init=T())
Inclusive scan.
template<typename T , class Oper >
void exclusive_scan (vector< T > const &input, vector< T > &output, T init, Oper oper)
Exclusive scan.
template<typename T >
void exclusive_scan (vector< T > const &input, vector< T > &output, T init=T())
Exclusive scan.
template<class K , class Comp >
void sort (K &&keys, Comp comp)
Sorts the vector into ascending order.
template<class K >
void sort (vector< K > &keys)
Sorts the elements in keys and values into ascending key order.
template<class K , class V , class Comp >
void sort_by_key (K &&keys, V &&vals, Comp comp)
Sorts the elements in keys and values into ascending key order.
template<class K , class V >
void sort_by_key (vector< K > &keys, vector< V > &vals)
Sorts the elements in keys and values into ascending key order.
template<typename val_t , typename col_t , typename idx_t >
inline_spmv< SpMat< val_t,
col_t, idx_t >, vector< val_t > > make_inline (const additive_operator<SpMat< val_t, col_t, idx_t >, vector< val_t > > &base)
Inlines a sparse matrix - vector product.
double device_spmv_perf (const backend::command_queue &q)
Weights device wrt to additive_operator performance.
template<typename T >
additive_operator<stencil< T >
, vector< T > > operator* (const stencil< T > &s, const vector< T > &x)
Convolve the stencil with the vector.
template<typename T >
additive_operator<stencil< T >
, vector< T > > operator* (const vector< T > &x, const stencil< T > &s)
Convolve the stencil with the vector.
template<size_t Tag, class Expr >
auto tag (const Expr &expr) -> const tagged_terminal< Tag, >
Tags terminal with a unique (in a single expression) tag.
template<size_t Tag, typename T , class Expr >
temporary< T, Tag, Expr >::type make_temp (const Expr &expr)
Create temporary to be reused in a vector expression.
template<size_t Tag, class Expr >
temporary< typename
detail::return_type< Expr >
::type, Tag, Expr > make_temp (const Expr &expr)
Create temporary to be reused in a vector expression.
template<class Condition , class Message >
void precondition (const Condition &condition, const Message &fail_message)
Check run-time condition.
size_t nextpow2 (size_t x)
Return next power of 2.
size_t alignup (size_t n, size_t m=16U)
Align n to the next multiple of m.
template<class T , class... Tail>
std::array< T, 1+sizeof...(Tail)> make_array (T t, Tail...tail)
Create std::array from arguments.
double device_vector_perf (const backend::command_queue &)
Weights device wrt to vector performance.
double equal_weights (const backend::command_queue &)
Assigns equal weight to each device.
void set_partitioning (std::function< double(const backend::command_queue &) > f)
Partitioning scheme for vectors and matrices.
std::vector< size_t > partition (size_t n, const std::vector< backend::command_queue > &queue)
Returns partitioning for the specified vector size on a given set of queues.
template<class T >
void copy (const vex::vector< T > &dv, std::vector< T > &hv, bool blocking=true)
Copy device vector to host vector.
template<class T >
void copy (const vex::vector< T > &dv, T *hv, bool blocking=true)
Copy device vector to host pointer.
template<class T >
void copy (const std::vector< T > &hv, vex::vector< T > &dv, bool blocking=true)
Copy host vector to device vector.
template<class T >
void copy (const T *hv, vex::vector< T > &dv, bool blocking=true)
Copy host pointer to device vector.
template<class InputIterator , class OutputIterator >
OutputIterator copy (InputIterator first, InputIterator last, OutputIterator result, bool blocking=true)
Copy range from device vector to host vector.
template<typename T >
void swap (vector< T > &x, vector< T > &y)
Swap two vectors.
template<class T >
std::ostream & operator<< (std::ostream &o, const vex::vector< T > &t)
Download and print the vector elements.
template<typename T >
vector_pointer< T > raw_pointer (const vector< T > &v)
Cast vex::vector to a raw pointer.
template<class Expr >
expr_permutation< Expr > permutation (const Expr &expr)
Returns permutation functor which is based on an integral expression.
template<class RDC , typename Expr , size_t NDIM, size_t NR>
reduced_vector_view< Expr,
NDIM, NR, RDC > reduce (const vector_view< Expr, gslice< NDIM > > &view, const std::array< size_t, NR > &reduce_dims)
Reduce vector_view along specified dimensions.
template<class RDC , typename Expr , size_t NDIM>
reduced_vector_view< Expr,
NDIM, 1, RDC > reduce (const vector_view< Expr, gslice< NDIM > > &view, size_t reduce_dim)
Reduce vector_view along specified dimension.
template<class RDC , typename Expr , size_t NDIM, size_t NR>
reduced_vector_view< typename
boost::proto::result_of::as_child
< const Expr, vector_domain >
::type, NDIM, NR, RDC > reduce (const gslice< NDIM > &slice, const Expr &expr, const std::array< size_t, NR > &reduce_dims)
Reduce sliced expression along specified dimensions.
template<class RDC , typename Expr , size_t NDIM>
reduced_vector_view< typename
boost::proto::result_of::as_child
< const Expr, vector_domain >
::type, NDIM, 1, RDC > reduce (const gslice< NDIM > &slice, const Expr &expr, size_t reduce_dim)
Reduce sliced expression along specified dimension.
template<class RDC , typename Expr , size_t NDIM, size_t NR>
reduced_vector_view< typename
boost::proto::result_of::as_child
< const Expr, vector_domain >
::type, NDIM, NR, RDC > reduce (const extent_gen< NDIM > &ext, const Expr &expr, const std::array< size_t, NR > &reduce_dims)
Reduce sliced expression along specified dimensions.
template<class RDC , typename Expr , size_t NDIM, size_t NR>
reduced_vector_view< typename
boost::proto::result_of::as_child
< const Expr, vector_domain >
::type, NDIM, NR, RDC > reduce (const extent_gen< NDIM > &ext, const Expr &expr, const extent_gen< NR > &reduce_dims)
Reduce sliced expression along specified dimensions.
template<class RDC , typename Expr , size_t NDIM>
reduced_vector_view< typename
boost::proto::result_of::as_child
< const Expr, vector_domain >
::type, NDIM, 1, RDC > reduce (const extent_gen< NDIM > &ext, const Expr &expr, size_t reduce_dim)
Reduce sliced expression along specified dimension.
template<class Expr , size_t Nout, size_t Nin>
auto reshape (const Expr &expr, const std::array< size_t, Nout > &dst_dims, const std::array< size_t, Nin > &src_dims) -> decltype(vex::permutation(detail::reshape_helper< Nout, Nin >(dst_dims, src_dims)())(expr))
Reshapes given expression.
template<class Expr , size_t Nout, size_t Nin>
auto reshape (const Expr &expr, const extent_gen< Nout > &dst_dims, const extent_gen< Nin > &src_dims) -> decltype(vex::permutation(detail::reshape_helper< Nout, Nin >(dst_dims.dim, src_dims.dim)())(expr))
Reshapes given expression.
Variables
const range _
Placeholder for an unbounded range.
const extent_gen< 0 > extents
Helper object for specifying slicer dimensions.
const index_gen< 0 > indices
Helper object for specifying slicer shape.
Detailed Description
Vector expression template library for OpenCL.
Function Documentation
template<class InputIterator , class OutputIterator > OutputIterator vex::copy (InputIterator first, InputIterator last, OutputIterator result, bool blocking = true)
Copy range from device vector to host vector.
Copy range from host vector to device vector.
double vex::device_spmv_perf (const backend::command_queue & q) inline
Weights device wrt to additive_operator performance.
Launches the following kernel on each device:
* y = A * x;
*
where x and y are vectors, and A is matrix for 3D Poisson problem in square domain. Each device gets portion of the vector proportional to the performance of this operation.
References vex::SpMat< val_t, col_t, idx_t >::apply(), vex::profiler< Clock >::tic_cl(), and vex::profiler< Clock >::toc().
double vex::device_vector_perf (const backend::command_queue & q) inline
Weights device wrt to vector performance.
Returns device weight after simple bandwidth test.
Launches the following kernel on each device:
* a = b + c;
*
where a, b and c are device vectors. Each device gets portion of the vector proportional to the performance of this operation.
References vex::profiler< Clock >::tic_cl(), and vex::profiler< Clock >::toc().
elem_index vex::element_index (size_t offset = 0, size_t length = 0)
When used in vector expression, returns current element index plus offset.
Parameters
offset Element indices will start from this value.
length Specify length of vector expression. This is only relevant when parent expression does not contain any vectors. See monte_carlo_pi test in tests/random.cpp for an example.
double vex::equal_weights (const backend::command_queue &) inline
Assigns equal weight to each device.
This results in equal partitioning.
template<typename val_t , typename col_t , typename idx_t > inline_spmv< SpMat<val_t, col_t, idx_t>, vector<val_t> > vex::make_inline (const additive_operator<SpMat< val_t, col_t, idx_t >, vector< val_t > > & base)
Inlines a sparse matrix - vector product.
When applied to a matrix-vector product, the product becomes inlineable. That is, it may be used in any vector expression (not just additive expression). This is only possible in single-device contexts, so user has to guarantee that.
Example:
* // Get maximum residual value:
* eps = sum(fabs(f - vex::make_inline(A * x)));
*
References precondition().
template<size_t Tag, typename T , class Expr > temporary<T, Tag, Expr> ::type vex::make_temp (const Expr & expr)
Create temporary to be reused in a vector expression.
The type of the temporary is explicitly specified.
template<size_t Tag, class Expr > temporary<typename detail::return_type<Expr>::type, Tag, Expr> vex::make_temp (const Expr & expr)
Create temporary to be reused in a vector expression.
The type of the temporary is automatically deduced from the supplied expression.
template<class Expr > expr_permutation<Expr> vex::permutation (const Expr & expr)
Returns permutation functor which is based on an integral expression.
Example:
* auto reverse = vex::permutation(N - 1 - vex::element_index());
* Y = reverse(X);
*
Referenced by vex::SpMat< val_t, col_t, idx_t >::apply(), and reshape().
template<class Condition , class Message > void vex::precondition (const Condition & condition, const Message & fail_message) inline
Check run-time condition.
Throws std::runtime_error if condition is false
Referenced by vex::Context::Context(), exclusive_scan(), inclusive_scan(), make_inline(), vex::gslice< NR >::operator()(), raw_pointer(), and vex::vector< T >::vector().
void vex::push_compile_options (const backend::command_queue & q, const std::string & str) inline
Set global compute kernel compilation options for a given device.
This replaces any previously set options. To roll back, call pop_compile_options().
void vex::push_program_header (const backend::command_queue & q, const std::string & str) inline
Set global compute kernel header for a given device.
This replaces any previously set header. To roll back, call pop_program_header().
template<typename T > vector_pointer<T> vex::raw_pointer (const vector< T > & v)
Cast vex::vector to a raw pointer.
Useful when user wants to get a pointer to a vector instead of its current element inside a vector expression. Could be combined with calls to address_of/dereference operators or with user-defined functions iterating through the vector. See examples in tests/vector_pointer.cpp.
References vex::vector< T >::nparts(), and precondition().
template<class Expr , size_t Nout, size_t Nin> auto vex::reshape (const Expr & expr, const std::array< size_t, Nout > & dst_dims, const std::array< size_t, Nin > & src_dims) -> decltype(vex::permutation(detail::reshape_helper<Nout, Nin>(dst_dims, src_dims)())(expr))
Reshapes given expression.
Makes a multidimensional expression of dst_dims dimensions from input expression shaped as specified by src_dim.
Parameters
expr Input expression
dst_dims dimensions of the resulting expression.
src_dims dimensions of the input expressions. Specified as positions in dst_dims.
Example:
* // Matrix transposition:
* auto B = reshape(A, make_array<size_t>(n, m), make_array(1, 0));
*
* // Expand 1D vector to a 2D matrix (by copying along redundant dimension):
* auto A = reshape(x, make_array(n, m), make_array(0));
*
References permutation().
template<class Expr , size_t Nout, size_t Nin> auto vex::reshape (const Expr & expr, const extent_gen< Nout > & dst_dims, const extent_gen< Nin > & src_dims) -> decltype(vex::permutation(detail::reshape_helper<Nout, Nin>(dst_dims.dim, src_dims.dim)())(expr))
Reshapes given expression.
Makes a multidimensional expression of dst_dims dimensions from input expression shaped as specified by src_dim.
Parameters
expr Input expression
dst_dims dimensions of the resulting expression.
src_dims dimensions of the input expressions. Specified as positions in dst_dims.
Example:
* // Matrix transposition:
* auto B = reshape(A, extents[n][m], extents[1][0]);
*
* // Expand 1D vector to a 2D matrix (by copying along redundant dimension):
* auto A = reshape(x, extents[n][m], extents[0]);
*
References permutation().
void vex::set_partitioning (std::function< double(const backend::command_queue &) > f) inline
Partitioning scheme for vectors and matrices.
Should be set once before any object of vector or matrix type is declared. Otherwise default parttioning function (partition_by_vector_perf) is selected.
template<typename T > void vex::sort (vex::vector< T > & x)
Sort.
If there are more than one device in vector's queue list, then all partitions are sorted individually on GPUs and then merged on CPU.
References copy(), vex::vector< T >::part_size(), vex::vector< T >::part_start(), vex::vector< T >::queue_list(), and vex::vector< T >::size().
Referenced by sort().
template<class K , class Comp > void vex::sort (K && keys, Comp comp)
Sorts the vector into ascending order.
Parameters
comp comparison function.
template<class K , class V , class Comp > void vex::sort_by_key (K && keys, V && vals, Comp comp)
Sorts the elements in keys and values into ascending key order.
Parameters
comp comparison function.
Referenced by sort_by_key().
template<size_t Tag, class Expr > auto vex::tag (const Expr & expr) -> const tagged_terminal< Tag, >
Tags terminal with a unique (in a single expression) tag.
By tagging terminals user guarantees that the terminals with same tags actually refer to the same data. VexCL is able to use this information in order to reduce number of kernel parameters and unnecessary global memory I/O operations.
Example:
* s = sum(tag<1>(x) * tag<1>(x) + tag<2>(y) * tag<2>(y));
*
template<class... Expr> expression_tuple< std::tuple<const Expr&...> > vex::tie (const Expr &... expr)
Ties several vector expressions into writeable tuple.
The following example results in a single kernel:
* vex::vector<double> x(ctx, 1024);
* vex::vector<double> y(ctx, 1024);
*
* vex::tie(x,y) = std::tie(x + y, y - x);
*
This is functionally equivalent to
* tmp_x = x + y;
* tmp_y = y - x;
* x = tmp_x;
* y = tmp_y;
*
but does not use temporaries and is more efficient.
Referenced by vex::generator::build_kernel(), vex::Context::Context(), vex::generator::make_function(), vex::mba< NDIM, real >::operator()(), and vex::generator::Kernel< NP >::operator()().